-- DROP TABLE public.api_key;
-- DROP TABLE public.api_admin;
-- DROP TABLE public.grant_funding_organisation;
-- DROP TABLE public.gap_user;

CREATE TABLE gap_user
(
    gap_user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_sub varchar(255) NULL,
    CONSTRAINT gap_user_pkey PRIMARY KEY (gap_user_id)
);

CREATE TABLE grant_funding_organisation
(
    funder_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    organisation_name character varying(250) NOT NULL,
    CONSTRAINT grant_funding_organisation_pkey PRIMARY KEY (funder_id)
);

CREATE TABLE grant_admin
(
    grant_admin_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    funder_id integer,
    user_id integer,
    CONSTRAINT grant_admin_pkey PRIMARY KEY (grant_admin_id),
    CONSTRAINT fk_gap_user_grant_admin FOREIGN KEY (user_id)
        REFERENCES public.gap_user (gap_user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_funding_org_grant_admin FOREIGN KEY (funder_id)
        REFERENCES public.grant_funding_organisation (funder_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.api_key (
	api_key_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	funder_id int4 NOT NULL,
	api_key_value varchar(128) NOT NULL,
	api_key_name varchar(1024) NOT NULL,
	api_key_description text NULL,
	created_date timestamp NULL,
	is_revoked bool NULL,
	revocation_date timestamp NULL,
	revoked_by int4 NULL,
	api_gateway_id varchar(50) NOT NULL,
	CONSTRAINT api_key_pkey PRIMARY KEY (api_key_id)
);
CREATE INDEX api_key_value_index ON public.api_key USING btree (api_key_value);

ALTER TABLE public.api_key ADD CONSTRAINT grant_funding_organisation_fk FOREIGN KEY (funder_id) REFERENCES public.grant_funding_organisation(funder_id);

INSERT INTO public.gap_user (gap_user_id, user_sub) VALUES(1, 'tco.cypress.test.technical.support');
INSERT INTO public.gap_user (gap_user_id, user_sub) VALUES(2, 'tco.cypress.test.super.admin');
INSERT INTO public.gap_user (gap_user_id, user_sub) VALUES(3, 'tco.cypress.test.technical.support.2');

INSERT INTO public.grant_funding_organisation (funder_id, organisation_name) VALUES(1, 'Test Org');
INSERT INTO public.grant_funding_organisation (funder_id, organisation_name) VALUES(2, 'Evil Org');
INSERT INTO public.grant_funding_organisation (funder_id, organisation_name) VALUES(3, 'Another Org');

INSERT INTO public.grant_admin (grant_admin_id, funder_id, user_id) VALUES(1, 1, 1);
INSERT INTO public.grant_admin (grant_admin_id, funder_id, user_id) VALUES(2, 1, 2);
INSERT INTO public.grant_admin (grant_admin_id, funder_id, user_id) VALUES(3, 2, 3);

