name: Java CI with Maven

on:
  push:
    branches:
      - feature/**
      - TMI2-**
      - bug/**
  pull_request:
    branches:
      - feature/**
      - TMI2-**
      - bug/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn package --file pom.xml

# TODO uncomment
#      - name: DependencyCheck
#        uses: dependency-check/Dependency-Check_Action@main
#        env:
#          JAVA_HOME: /opt/jdk
#        id: DependencyCheck
#        with:
#          project: "gap-find-api-admin"
#          path: "."
#          format: "HTML"
#          args: >
#            --enableRetired
#            --disableOssIndex true
#
#      - name: Upload Test results
#        uses: actions/upload-artifact@master
#        with:
#          name: DependencyCheck report
#          path: ${{github.workspace}}/reports
#
#      - name: Unit tests
#        run: mvn test

      - name: Read .nvmrc
        working-directory: src/test/e2e
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Read yarn cache directory path
        working-directory: src/test/e2e
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
        id: yarn-cache-dir-path

#      - name: Cache dependencies
#        working-directory: src/test/e2e
#        uses: actions/cache@v2
#        id: yarn-cache
#        with:
#          path: |
#            ${{ steps.yarn-cache-dir-path.outputs.dir }}
#            **/node_modules
#            ~/.cache/Cypress
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-

      - name: Install yarn
        working-directory: src/test/e2e
        run: yarn install


      - name: Setup cypress test environment
        run: |
          echo "BANANA"
          docker ps -a
          docker build -t gap-find-api-admin .
          echo "PINEAPPLE"
          docker ps -a
          docker compose -f docker-compose.yml up -d
          echo "PEACH"
          docker ps -a

      - name: Run cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: src/test/e2e
          config-file: cypress.config.js
          record: false
          wait-on: 'http://localhost:8084'
          wait-on-timeout: 60
          browser: chrome
          runTests: true
          spec: cypress/e2e/*

