name: Java CI with Maven

on:
  push:
    branches:
      - feature/**
      - TMI2-**
      - bug/**
  pull_request:
    branches:
      - feature/**
      - TMI2-**
      - bug/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: |
          echo ANANAS
          pwd
          ls -la
          mvn package --file pom.xml

# TODO uncomment
#      - name: DependencyCheck
#        uses: dependency-check/Dependency-Check_Action@main
#        env:
#          JAVA_HOME: /opt/jdk
#        id: DependencyCheck
#        with:
#          project: "gap-find-api-admin"
#          path: "."
#          format: "HTML"
#          args: >
#            --enableRetired
#            --disableOssIndex true
#
#      - name: Upload Test results
#        uses: actions/upload-artifact@master
#        with:
#          name: DependencyCheck report
#          path: ${{github.workspace}}/reports
#
#      - name: Unit tests
#        run: mvn test

      - name: Read .nvmrc
        working-directory: src/test/e2e
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Read yarn cache directory path
        working-directory: src/test/e2e
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
        id: yarn-cache-dir-path

#      - name: Cache dependencies
#        working-directory: src/test/e2e
#        uses: actions/cache@v2
#        id: yarn-cache
#        with:
#          path: |
#            ${{ steps.yarn-cache-dir-path.outputs.dir }}
#            **/node_modules
#            ~/.cache/Cypress
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-

      - name: Install yarn
        working-directory: src/test/e2e
        run: yarn install

      - name: Generate .env for docker file
        run: |
          cat << EOF > .env
          AWS_API_GATEWAY_ID=${{ secrets.AWS_API_GATEWAY_ID }}
          AWS_API_GATEWAY_USAGE_PLAN_ID=${{ secrets.AWS_API_GATEWAY_USAGE_PLAN_ID }}
          AWS_SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          EOF

      - name: Setup cypress test environment
        run: |
          docker build -t gap-find-api-admin .
          docker compose -f docker-compose.yml up -d
          docker network inspect gap-find-api-admin_testing-network
          

      - name: Let's nap for 30 seconds to make sure the app has started
        run: |
          sleep 30

      - name: check app is running and wiremock is fine
        run: |
          echo hitting localhost:8082/__admin/mappings
          curl http://localhost:8082/__admin/mappings
          echo hitting gap-find-api-admin/find/api/admin/health
          curl http://gap-find-api-admin/find/api/admin/health
          echo hitting wiremock/__admin/mappings
          curl http://wiremock/__admin/mappings

      - name: Run cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: src/test/e2e/
          config-file: cypress.config.js
          record: false
          browser: chrome
          runTests: true
          spec: cypress/e2e/technicalSupport/*


